apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: cloudflare
  labels:
    app: ldn-ui
  name: ldn-ui-www
  namespace: learndevopsnow
spec:
  ingressClassName: nginx
  rules:
    - host: www.learndevopsnow-mm.blog
      http:
        paths:
          - backend:
              service:
                name: ldn-ui
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - www.learndevopsnow-mm.blog
      secretName: tls-secret-ldn-mm

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: cloudflare
  labels:
    app: ldn-ui
  name: ldn-ui-root
  namespace: learndevopsnow
spec:
  ingressClassName: nginx
  rules:
    - host: learndevopsnow-mm.blog
      http:
        paths:
          - backend:
              service:
                name: ldn-ui
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - learndevopsnow-mm.blog
      secretName: tls-secret-ldn-mm-root